name: Build Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        ports:
          - 5433:5432
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          POSTGRES_DB: ${{ vars.POSTGRES_DB }}
        options: >-
          --health-cmd "pg_isready -U ${{vars.POSTGRES_USER}}"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Log in to Docker Hub (optional, if pushing images)
      - uses: actions/checkout@v3
      - name: Login to ghcr.io
        run: |
          echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Set up Docker Buildx for multi-platform builds (optional)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build the backend image
      - name: Build Backend Image
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
          ENV VITE_ENV: production
          ENV NODE_ENV: production
          ENV VITE_API_URL: http://planer-api.klimahanf.de
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_INVITE_SECRET: ${{ secrets.JWT_INVITE_SECRET }}
          JWT_RESET_SECRET: ${{ secrets.JWT_RESET_SECRET }}
          JWT_FARM_SECRET: ${{ secrets.JWT_FARM_SECRET }}
          JWT_SCHEDULER_SECRET: ${{ secrets.JWT_SCHEDULER_SECRET }}
          GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
        run: |
          docker build \
            -t litefarm-backend \
            -f ./packages/api/prod.Dockerfile \
            ./packages/

      # Build the frontend image
      - name: Build Frontend Image
        env:
          VITE_GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
        run: |
          docker build \
            -t litefarm-frontend \
            -f ./packages/webapp/prod.Dockerfile \
            ./packages/

      # (Optional) Push images to Docker Hub
      - name: Push Backend Image to Docker Hub
        run: |
          docker tag litefarm-backend ghcr.io/yuszuv/litefarm-backend:latest
          docker push ghcr.io/yuszuv/litefarm-backend:latest

      - name: Push Frontend Image to Docker Hub
        run: |
          docker tag litefarm-frontend ghcr.io/yuszuv/litefarm-frontend:latest
          docker push ghcr.io/yuszuv/litefarm-frontend:latest
