name: Build Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        ports:
          - 5433:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Log in to Docker Hub (optional, if pushing images)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Set up Docker Buildx for multi-platform builds (optional)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build the backend image
      - name: Build Backend Image
        run: |
          docker build \
            -t litefarm-backend \
            -f ./packages/api/prod.Dockerfile \
            ./packages/

      # Build the frontend image
      - name: Build Frontend Image
        run: |
          docker build \
            -t litefarm-frontend \
            -f ./packages/webapp/prod.Dockerfile \
            ./packages/

      # (Optional) Push images to Docker Hub
      - name: Push Backend Image to Docker Hub
        run: |
          docker tag litefarm-backend yourdockerhubusername/litefarm-backend:latest
          docker push yourdockerhubusername/litefarm-backend:latest

      - name: Push Frontend Image to Docker Hub
        run: |
          docker tag litefarm-frontend yourdockerhubusername/litefarm-frontend:latest
          docker push yourdockerhubusername/litefarm-frontend:latest
