name: Build Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        ports:
          - 5433:5432
        env:
          POSTGRES_PASSWORD: { { secrets.POSTGRES_PASSWORD } }
          POSTGRES_USER: { { env.POSTGRES_USER } }
          POSTGRES_DB: { { env.POSTGRES_DB } }
        options: >-
          --health-cmd "pg_isready -U {{env.POSTGRES_USER}}"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Log in to Docker Hub (optional, if pushing images)
      - uses: actions/checkout@v3
      - name: Login to ghcr.io
        run: |
          echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Set up Docker Buildx for multi-platform builds (optional)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build the backend image
      - name: Build Backend Image
        run: |
          docker build \
            -t litefarm-backend \
            -f ./packages/api/prod.Dockerfile \
            ./packages/

      # Build the frontend image
      - name: Build Frontend Image
        run: |
          docker build \
            -t litefarm-frontend \
            -f ./packages/webapp/prod.Dockerfile \
            ./packages/

      # (Optional) Push images to Docker Hub
      - name: Push Backend Image to Docker Hub
        run: |
          docker tag litefarm-backend ghcr.io/yuszuv/litefarm-backend:latest
          docker push ghcr.io/yuszuv/litefarm-backend:latest

      - name: Push Frontend Image to Docker Hub
        run: |
          docker tag litefarm-frontend ghcr.io/yuszuv/litefarm-frontend:latest
          docker push ghcr.io/yuszuv/litefarm-frontend:latest
